name 'gemtest'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures gemtest'
long_description 'Installs/Configures gemtest'
version '0.1.0'
